export const ErrorCode = {
  INVALID_PARAMS: 'INVALID_PARAMS',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  PASSWORD_TOO_SMALL: 'PASSWORD_TOO_SMALL',
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  UNKNOWN: 'UNKNOWN',
  INVALID_EMAIL_ERROR: 'INVALID_EMAIL_ERROR',
  USER_WAS_NOT_FOUND: 'USER_WAS_NOT_FOUND',
  WRONG_PASSWORD_ERROR: 'WRONG_PASSWORD_ERROR',
  SHIPMENT_ALREADY_EXISTS: 'SHIPMENT_ALREADY_EXISTS',
  SHIPMENT_NOT_FOUND: 'SHIPMENT_NOT_FOUND',
  MEETUP_ALREADY_EXISTS: 'MEETUP_ALREADY_EXISTS',
  MEETUP_NOT_FOUND: 'MEETUP_NOT_FOUND',
}
